development:
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] || 'boardy_dev' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'magic' %>
  host: <%= ENV['DATABASE_HOST'] || 'mysql.service.bcdev' %>

production:
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] || 'boardy_production' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'magic' %>
  host: <%= ENV['DATABASE_HOST'] || 'mysql.service.dev' %>

test:
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] || 'boardy_test' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'magic' %>
  host: <%= ENV['DATABASE_HOST'] || 'mysql.service.bcdev' %>
